let syllabi=[],filtered=[];
const faculty=document.getElementById("facultySelect"),programme=document.getElementById("programmeSelect"),year=document.getElementById("yearSelect"),category=document.getElementById("categorySelect"),semester=document.getElementById("semesterSelect"),search=document.getElementById("searchInput"),clearSearch=document.getElementById("clearSearch"),resetButton=document.getElementById("resetButton"),emptyReset=document.getElementById("emptyReset"),results=document.getElementById("resultsContainer"),resultCount=document.getElementById("resultCount"),noResults=document.getElementById("noResults"),themeToggle=document.getElementById("themeToggle");

async function loadData(){try{const response=await fetch("./data/syllabi.json",{cache:"no-store"});if(!response.ok)throw new Error("Could not load data");syllabi=await response.json();filtered=[...syllabi];createFilters();render()}catch(e){console.error(e);results.innerHTML='<div class="empty"><div>⚠️</div><h3>Data could not be loaded</h3><p>Please try again later.</p></div>'}}
function unique(values){return [...new Set(values.filter(Boolean).map(String))]}
function fillSelect(el,values,defaultText){el.innerHTML="";const d=document.createElement("option");d.value="";d.textContent=defaultText;el.appendChild(d);values.forEach(v=>{const o=document.createElement("option");o.value=v;o.textContent=v;el.appendChild(o)})}
function createFilters(){fillSelect(faculty,unique(syllabi.map(x=>x.faculty)),"All Faculties");fillSelect(programme,unique(syllabi.map(x=>x.programme)),"All Programmes");fillSelect(year,unique(syllabi.map(x=>x.academicYear)).sort().reverse(),"All Years");fillSelect(category,unique(syllabi.map(x=>x.category)),"All Categories");const s=[];syllabi.forEach(x=>{const a=Number(x.semesterFrom),b=Number(x.semesterTo);if(a&&b)for(let i=a;i<=b;i++)s.push(i)});fillSelect(semester,[...new Set(s)].sort((a,b)=>a-b),"All Semesters")}
function applyFilters(){const fv=faculty.value,pv=programme.value,yv=year.value,cv=category.value,sv=Number(semester.value),q=search.value.trim().toLowerCase();filtered=syllabi.filter(x=>{if(fv&&x.faculty!==fv)return false;if(pv&&x.programme!==pv)return false;if(yv&&x.academicYear!==yv)return false;if(cv&&x.category!==cv)return false;if(sv){const a=Number(x.semesterFrom),b=Number(x.semesterTo);if(!a||!b||sv<a||sv>b)return false}if(q){const t=[x.title,x.faculty,x.programme,x.category,x.academicYear,...(x.programmeType||[])].join(" ").toLowerCase();if(!t.includes(q))return false}return true});render()}
function semesterText(x){const a=Number(x.semesterFrom),b=Number(x.semesterTo);if(!a||!b)return"See document";return a===b?`Semester ${a}`:`Semesters ${a}–${b}`}
function escapeHTML(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function safeURL(v){try{const u=new URL(v);return["https:","http:"].includes(u.protocol)?u.href:"#"}catch{return"#"}}
function render(){results.innerHTML="";resultCount.textContent=filtered.length;if(!filtered.length){noResults.classList.remove("hidden");return}noResults.classList.add("hidden");filtered.forEach(x=>{const card=document.createElement("article");card.className="card";const type=Array.isArray(x.programmeType)?x.programmeType.join(", "):"";card.innerHTML=`<div class="card-header"><span class="category">${escapeHTML(x.category||"Syllabus")}</span><span class="year">${escapeHTML(x.academicYear||"")}</span></div><h3>${escapeHTML(x.title||"Untitled syllabus")}</h3><div class="info"><span>🏛️ ${escapeHTML(x.faculty||"—")}</span><span>🎓 ${escapeHTML(x.programme||"—")}</span>${type?`<span>📚 ${escapeHTML(type)}</span>`:""}<span>📖 ${semesterText(x)}</span></div><div class="actions">${x.pdfUrl?`<a class="primary-button" href="${safeURL(x.pdfUrl)}" target="_blank" rel="noopener noreferrer">📄 View Syllabus</a>`:""}<a class="secondary-button" href="${safeURL(x.sourceUrl)}" target="_blank" rel="noopener noreferrer">PU Source ↗</a></div>`;results.appendChild(card)})}
function resetAll(){faculty.value="";programme.value="";year.value="";category.value="";semester.value="";search.value="";filtered=[...syllabi];render()}
function loadTheme(){if(localStorage.getItem("pu-theme")==="dark"){document.body.classList.add("dark");themeToggle.textContent="☀️"}}
function toggleTheme(){document.body.classList.toggle("dark");const d=document.body.classList.contains("dark");localStorage.setItem("pu-theme",d?"dark":"light");themeToggle.textContent=d?"☀️":"🌙"}
[faculty,programme,year,category,semester].forEach(x=>x.addEventListener("change",applyFilters));search.addEventListener("input",applyFilters);clearSearch.addEventListener("click",()=>{search.value="";applyFilters();search.focus()});resetButton.addEventListener("click",resetAll);emptyReset.addEventListener("click",resetAll);themeToggle.addEventListener("click",toggleTheme);loadTheme();loadData();
